### ISSUE TITLE
chef-server-ctl install opscode-manage failing with -->> ChefNoMethodError: undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by uditjh** [chef-cookbooks/chef-server#110]
Please ignore my error as I know this isn't the right place to report this but this is related to the chef server installation. The initial install on CentOS 6 went fine using chef-solo and this cookbook but "chef-server-ctl install opscode-manage" is failing with an error in the private-chef cookbook which I'm not able to find anywhere on github or supermarket. Any ideas?

Complete stack trace below:

Generated at 2015-12-09 21:33:35 +0000
NoMethodError: yum_package[opscode-manage] (private-chef::add_ons_remote line 16) had an error: NoMethodError: undefined method `>' for nil:NilClass
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum.rb:1075:in `yum_command'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum.rb:1258:in `install_remote_package'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum.rb:1269:in `install_package'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:91:in `block (2 levels) in action_install'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:217:in `multipackage_api_adapter'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:90:in `block in action_install'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:175:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package.rb:89:in `action_install'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:589:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:658:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:692:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:271:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:229:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:386:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'

**Comment by james-s-nduka** [comment]
Receiving this exact same issue. Odd because is this worked previously.

**Comment by james-s-nduka** [comment]
curl -s https://packagecloud.io/install/repositories/chef/stable/script.rpm.sh | sudo bash 
sudo yum install opscode-manage
chef-server-ctl reconfigure
opscode-manage-ctl reconfigure

The above is a workaround that should be helpful.

**Comment by hrnmm** [comment]
thanks james. your workaround worked for me

**Comment by donbecker** [comment]
@james-s-nduka that worked for me as well on CentOS 6.6.

**Comment by tas50** [comment]
we're currently testing this scenario in the 5.0 release which uses a newer chef-ingredient cookbook, with a lot of improvements.  I'm going to close this out unless someone is still encountering this problem with the 5.0 cookbook.
