### ISSUE TITLE
Upstream yum issue

### ISSUE THREAD

**Issue by rossedman** [chef-cookbooks/chef-server#113]
`yum-chef` recently did a big update change and this is effecting how this works. This dependency is coming from `chef-ingredient`. May need to lock that dependency in place until it can be addressed or a version can be bumped.

**Comment by tas50** [comment]
@rossedman What's the issue you're running into with yum-chef?

**Comment by tas50** [comment]
5.0 depends on the latest chef-ingredient now, which should resolve any issue you might have been seeing in the 4.X releases.
