### ISSUE TITLE
'chef-server-ctl reconfigure' fails when running on machine with IPv6 disabled

### ISSUE THREAD

**Issue by JamesDawson** [chef-cookbooks/chef-server#130]
### Cookbook version
5.0.1

### Chef-client version
12.15.19

### Platform Details
RedHat 7.0 (IPv6 disabled), running on VMware vSphere 5.5

### Scenario:
Using chef-provisioning to provision a new VM and install a standalone Chef server instance.

### Steps to Reproduce:
Disable IPv6 on the node (`echo "net.ipv6.conf.default.disable_ipv6 = 1" >>/etc/sysctl.conf`) and run the default recipe.

### Expected Result:
The chef run completes without error.

### Actual Result:
The following error is logged:

```
[2016-11-02T14:01:53+00:00] ERROR: chef_ingredient[chef-server] (chef-server::default line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[chef-server-core-reconfigure] (/var/chef/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb line 105) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process
to exit with [0], but received '1'
---- Begin output of chef-server-ctl reconfigure ----
STDOUT: [2016-11-02T14:01:52+00:00] FATAL: Errno::EADDRNOTAVAIL: Cannot assign requested address - bind(2) for [::1]:8889
STDERR:
---- End output of chef-server-ctl reconfigure ----
Ran chef-server-ctl reconfigure returned 1
[2016-11-02T14:01:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Some research has left me unsure as to whether this is an issue with this cookbook or with omnibus-ctl as, from what I understand, this is what is being used when invoking 'chef-server-ctl reconfigure' - either way I'm unsure as to if/how I can change this behaviour.

Setting the `ip_version` chef server configuration setting to `ipv4` made no difference to the above behaviour.

**Comment by tas50** [comment]
This is actually a chef-server issue and not an issue in this particular cookbook. If you're still having this problem with the latest chef server please file a but here: https://github.com/chef/chef-server
