### ISSUE TITLE
version contraint error - Net::HTTPServerException: 412 "Precondition Failed"

### ISSUE THREAD

**Issue by onedumslack** [chef-cookbooks/chef-server#136]
Are there more steps that need to be completed to use this cookbook with chef-solo?  I have followed the instructions from the readme without modification and have also tried running from a wrapper cookbook to provide custom chef-server.rb configs and I get the same result.  I have tried this with the amazon linux ami and the centos 6 marketplace ami.

### Cookbook version
5.2.0

### Chef-client version
12.19.36

### Platform Details
Centos 6

### Scenario:
chef-solo -o 'recipe[chef-server::default]'

### Steps to Reproduce:
clean ami install of centos 6 from amazon marketplace.
Then directly from the README

curl -L https://www.chef.io/chef/install.sh | sudo bash
sudo mkdir -p /var/chef/cache /var/chef/cookbooks
wget -qO- https://supermarket.chef.io/cookbooks/chef-server/download | sudo tar xvzC /var/chef/cookbooks
for dep in chef-ingredient yum-chef yum apt-chef apt packagecloud compat_resource
do
  wget -qO- https://supermarket.chef.io/cookbooks/${dep}/download | sudo tar xvzC /var/chef/cookbooks
done
sudo chef-solo -o 'recipe[chef-server::default]'

### Expected Result:
I thought it would take defaults and install latest version of chef-server-core with default config.

### Actual Result:
I receive this error:
Error Resolving Cookbooks for Run List:

Missing Cookbooks:
------------------
Could not satisfy version constraints for: chef-ingredient
Expanded Run List:
------------------
* chef-server::default

Platform:
---------
x86_64-linux

**Comment by onedumslack** [comment]
I got past the error.  It looks like something has changed with compatibility using the default chef-ingredient cookbook.  I had to download the 1.1.0 version and it runs ok now.

**Comment by stpitner** [comment]
I likewise was able to get past the error by downloading chef-ingredient 1.1.  I don't think it likes the major version bump in chef-ingredient.

**Comment by cheeseplus** [comment]
The issue here is you only looped on latest versions of the deps instead of respecting the dependency pin to `~> 1.1` in the metadata.rb. Using a tool like Berkshelf (via `berks vendor`) would be super useful here to make sure you're resolving the dependencies properly with respect to the cookbooks.

This isn't an issue with the cookbook as the dependencies are declared correctly. Closing.
