### ISSUE TITLE
 IPAddr::AddressFamilyError

### ISSUE THREAD

**Issue by rreilly-edr** [chef-cookbooks/chef-server#144]
### Cookbook version
5.4.0

### Chef-client version
13.5.3

### Platform Details
ubuntu 16.04 aws ec2
### Scenario:
Install chef server 

### Steps to Reproduce:
# install chef-solo
curl -L https://www.chef.io/chef/install.sh | sudo bash
# create required bootstrap dirs/files
sudo mkdir -p /var/chef/cache /var/chef/cookbooks
# pull down this chef-server cookbook
wget -qO- https://supermarket.chef.io/cookbooks/chef-server/download | sudo tar xvzC /var/chef/cookbooks
# pull down dependency cookbooks
for dep in chef-ingredient yum-chef yum apt-chef apt packagecloud compat_resource
do
  wget -qO- https://supermarket.chef.io/cookbooks/${dep}/download | sudo tar xvzC /var/chef/cookbooks
done
# GO GO GO!!!
sudo chef-solo -o 'recipe[chef-server::default]'

### Expected Result:
chef server installs
### Actual Result:
`  ================================================================================
aws_instance.chef-server (remote-exec):       Error executing action `run` on resource 'execute[chef-server-core-reconfigure]'
aws_instance.chef-server (remote-exec):       ================================================================================

aws_instance.chef-server (remote-exec):       Mixlib::ShellOut::ShellCommandFailed
aws_instance.chef-server (remote-exec):       ------------------------------------
aws_instance.chef-server (remote-exec):       Expected process to exit with [0], but received '1'
aws_instance.chef-server (remote-exec):       ---- Begin output of chef-server-ctl reconfigure ----
aws_instance.chef-server (remote-exec):       STDOUT: 
aws_instance.chef-server (remote-exec):       ================================================================================
aws_instance.chef-server (remote-exec):       Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb
aws_instance.chef-server (remote-exec):       ================================================================================
aws_instance.chef-server (remote-exec): 
aws_instance.chef-server (remote-exec):       IPAddr::AddressFamilyError
aws_instance.chef-server (remote-exec):       --------------------------
aws_instance.chef-server (remote-exec):       address family must be specified
aws_instance.chef-server (remote-exec): 
aws_instance.chef-server (remote-exec):       Cookbook Trace:
aws_instance.chef-server (remote-exec):       ---------------
aws_instance.chef-server (remote-exec):         /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/helper.rb:33:in `new'
aws_instance.chef-server (remote-exec):         /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/helper.rb:33:in `is_ip?'
aws_instance.chef-server (remote-exec):         /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:60:in `from_file'
aws_instance.chef-server (remote-exec):         /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:149:in `block in from_file'
aws_instance.chef-server (remote-exec):         /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:132:in `each'
aws_instance.chef-server (remote-exec):         /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:132:in `from_file'
aws_instance.chef-server (remote-exec): 
aws_instance.chef-server (remote-exec):       Relevant File Content:
aws_instance.chef-server (remote-exec):       ----------------------
aws_instance.chef-server (remote-exec):       /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/helper.rb:
aws_instance.chef-server (remote-exec):       
aws_instance.chef-server (remote-exec):        26:               end
aws_instance.chef-server (remote-exec):        27:
aws_instance.chef-server (remote-exec):        28:      config['actions_password'] = PrivateChef.credentials.get("rabbitmq", "actions_password")
aws_instance.chef-server (remote-exec):        29:      config
aws_instance.chef-server (remote-exec):        30:    end
aws_instance.chef-server (remote-exec):        31:
aws_instance.chef-server (remote-exec):        32:    def self.is_ip?(addr)
aws_instance.chef-server (remote-exec):        33>>     IPAddr.new addr
aws_instance.chef-server (remote-exec):        34:      true
aws_instance.chef-server (remote-exec):        35:    rescue IPAddr::InvalidAddressError
aws_instance.chef-server (remote-exec):        36:      false
aws_instance.chef-server (remote-exec):        37:    end
aws_instance.chef-server (remote-exec):        38:
aws_instance.chef-server (remote-exec):        39:    # Normalizes hosts. If the host part is an ipv6 literal, then it
aws_instance.chef-server (remote-exec):        40:    # needs to be quoted with []
aws_instance.chef-server (remote-exec):        41:    def self.normalize_host(host_part)
aws_instance.chef-server (remote-exec):        42:      # Make this simple: if ':' is detected at all, it is assumed
aws_instance.chef-server (remote-exec):       
aws_instance.chef-server (remote-exec):       Platform:
aws_instance.chef-server (remote-exec):       ---------
aws_instance.chef-server (remote-exec):       x86_64-linux
aws_instance.chef-server (remote-exec): 
`

**Comment by singhai0** [comment]
Just wondering why was this issue closed @rreilly-edr.
