### ISSUE TITLE
Chef-Automate Cookbook?

### ISSUE THREAD

**Issue by staticfrost** [chef-cookbooks/chef-server#150]
### Cookbook version
latest

### Chef-client version
latest

### Platform Details
CentOS

### Scenario:
I would like to know if someone has created Chef-Automate Cookbook?

### Expected Result:
the answer is yes, and a link is posted

### Actual Result:
you'll say no?

**Comment by tas50** [comment]
Chef-ingredient has resources for installing non open source Chef products. Give it a try
