### ISSUE TITLE
Wrong chef-ingredient dependency

### ISSUE THREAD

**Issue by limitusus** [chef-cookbooks/chef-server#151]
### Cookbook version
5.5.1

### Chef-client version
N/A

### Platform Details
N/A

### Scenario:

In metadata.rb
```ruby
depends 'chef-ingredient', '>= 2.1.10'
```
where README says `chef-ingredient >= 2.1.12`.

It looks chef-ingredient not yet released v2.1.12.

**Comment by iennae** [comment]
Thanks for reporting! I've resolved this.
