### ISSUE TITLE
Habitat-ized chef-server cookbook 

### ISSUE THREAD

**Issue by jsirex** [chef-cookbooks/chef-server#156]
Hello!

Do you have any plans to rewrite or create new chef server cookbook using habitat?
I see big potential in chef-client+habitat to install any software anywhere in similar approach, so I'm trying to unify my whole infrastructure including chef tools itself with habitat and chef-client.

**Comment by tas50** [comment]
That's probably not something we'd do here. There's certainly value in running chef-server as a habitat package and I believe we do have customers doing so. We wouldn't modify this cookbook to do so since people that wanted a habitized chef-server wouldn't really need the cookbook.
