### ISSUE TITLE
Problem when update to use Valid SSL cert

### ISSUE THREAD

**Issue by chrisduong** [chef-cookbooks/chef-server#72]
Hi,

I'm sorry if this is not a right place for my problem.
I switched from self-signed cert to a valid certificate. I stopped Chef Server, change certificate, run 'reconfigure', and then start the server. 
I was able to bootstrap a node with its FQDN, the client.pem created but it failed later.

public_name Starting first Chef Client run...
public_name Starting Chef Client, version 12.0.3
public_name [2015-02-25T04:41:15+00:00] ERROR: Server returned error 500 for https://chef.ABCD.com/organizations/ABCD/reports/nodes/internal_name/runs, retrying 1/5 in 4s
public_name [2015-02-25T04:41:19+00:00] ERROR: Server returned error 500 for https://chef.ABCD.com/organizations/ABCD/reports/nodes/internal_name/runs, retrying 2/5 in 8s
public_name [2015

I tracked in the reporting log - /var/log/opscode/opscode-reporting/current

2015-02-25_03:08:13.88725 Undefined:Undefined#Undefined [error] <0.555.0> SSL: certify: ssl_handshake.erl:239:Fatal error: certificate unknown

Does it relate to the different from <public_name> and <internal_name> that making the SSL handshake failed.
Thanks a ton

**Comment by jamesc** [comment]
@chrisduong Can you try an `opscode-reporting-ctl reconfigure` and then a `chef-server-ctl restart opscode-reporting`.

**Comment by chrisduong** [comment]
@jamesc, I tried that but still now working :(
Still the same error in opscode-reporting, certificate unknown.

**Comment by bleything** [comment]
I started getting this today right after I installed opscode-reporting. No combination of reconfiguring/uninstalling/cleansing reporting helps, no amount of reconfiguring chef-server helps :(

**Comment by chrisduong** [comment]
I have fixed it, but I don't remember what exactly fixed it.
There is couple of Chef Server component using SSL certs, but I'm not sure which of them.
The possible way is to reconfigure all Chef Server component (opscode-reporting, opcode-manage,...) and finally reconfigure Chef Server with chef-server-ctl, then restart Chef Server.
