### ISSUE TITLE
Does this CK trigger 'chef-server-ctl upgrade' after an install / upgrade ?

### ISSUE THREAD

**Issue by BarthV** [chef-cookbooks/chef-server#78]
Ohai !

Got this issue after upgrading my standalone server from 12.0.3 to 12.0.7 : 
https://github.com/chef/chef/issues/3171

Is it normal that I had to run ```chef-server-ctl upgrade``` by myself after the upgrade ?
Can we plan to add a specific resource to triggger this command when it's needed ?

Thanks !

**Comment by BarthV** [comment]
If it's not implemented 'by design' I'm ok with that, I'll do it in my wrapper.

**Comment by jtimberman** [comment]
That's not in scope for this cookbook. Perhaps you want [Chef support](mailto:support@chef.io) or [the Chef Server repository](https://github.com/chef/chef-server).
