### ISSUE TITLE
centos6 knife solo cook: Ran chef-server-ctl reconfigure returned 1

### ISSUE THREAD

**Issue by jslusher** [chef-cookbooks/chef-server#80]
I'm using the chef cookbook on a centos6 AMI. I'm getting an error in the rabbitmq cookbook:

https://gist.github.com/jslusher/028dfd88ab24fd9d16d5

It seems that the cookbook isn't installing the erlang properly:

If I try and run the embedded executable for rabbitmqctl by itself, I get this:

/opt/opscode/embedded/bin/rabbitmqctl
/opt/opscode/embedded/bin/rabbitmqctl: line 29: exec: erl: not found

**Comment by jslusher** [comment]
I installed erlang through epel manually and reran the cookbook, but it still isn't working. rabbitmq isn't starting for some reason.

**Comment by stevendanna** [comment]
@jslusher In order to run the rabbitmqctl executable, you'll need to put /opt/opscode/embedded/bin in your path.  The omnibus packages comes with erlang and erl should be in the embedded/bin directory.

**Comment by jslusher** [comment]
@stevendanna thank you for the reply. I'll try it out. So that's not something the chef-server cookbook accounts for?

**Comment by jtimberman** [comment]
The Chef Server is distributed as a full stack "omnibus" package that includes all the software it needs to operate. It won't use "system" erlang or rabbitmq packages, nor should it - we build and ship in the chef-server-core package tested versions of all the required software.

The output you're seeing indicates that perhaps there was a problem starting rabbitmq. The issues for this cookbook aren't a great support channel though, and you should email the [chef user mailing list](http://lists.opscode.com/sympa/info/chef), [Chef support](mailto:support@chef.io), or ask in irc.freenode.net/chef.
