### ISSUE TITLE
Centos test fails if you specify a version

### ISSUE THREAD

**Issue by luckymike** [chef-cookbooks/chef-server#82]
I noticed yesterday that my Centos kitchen tests failed when I specified a version of the Chef Server to install. I was able to reproduce by setting a version in the chef-server .kitchen.yml:

https://gist.github.com/luckymike/fbcc0661e27eece760e9

**Comment by acqant** [comment]
I'm seeing an issue with Centos 6.6 as well.

 Version 12.0.8 of chef-server-core not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)

 chef_server_ingredient("chef-server-core") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_server_ingredient
             cookbook_name "chef-server"
             recipe_name "default"
             version "12.0.8"
             package_name "chef-server-core"
           end


Yum install chef-server-core from command line works

**Comment by acqant** [comment]
My bad, I have the same issue I put a version in my wrapper cookbook.  I take it out and it works

 - install version 12.0.8-1.el6 of package chef-server-core

**Comment by jtimberman** [comment]
I think you need the `.el6` appended, perhaps? If not and this is still reproducible, please reopen. Thanks!

**Comment by luckymike** [comment]
Yeah, .el6 did it. Sorry I didn't update the issue.
