### ISSUE TITLE
Bad package name if you try to install chef 11

### ISSUE THREAD

**Issue by 8la** [chef-cookbooks/chef-server#83]
Hi,

This cookbook fails when you try to install chef 11 on Ubuntu 14. The reason is obvious because package names for chef12 (chef-server-core) and chef11 (chef-server) are different. 

This cookbooks uses `chef-server-package` as the package name on the resource provided by `chef-server-ingredient' so no chef11 installation will be possible.

**Comment by jtimberman** [comment]
As of [v3.0.0 of this cookbook](https://github.com/chef-cookbooks/chef-server/blob/master/CHANGELOG.md#v300-2015-02-24), it no longer supports Chef Server 11.

If you want to use it for Chef Server 11, you'll need to use v2.1.6.
