### ISSUE TITLE
Documentation request: add ons, example configuration, etc.

### ISSUE THREAD

**Issue by Joseph-R** [chef-cookbooks/chef-server#94]
Hey guys!

I'm walking through this for the first time, trying to stand up my own on-premises chef server using this cookbook and [chef-server-populator](https://github.com/hw-cookbooks/chef-server-populator) to get all my Chef server config fully in code.

Coming at this with completely fresh eyes, I'm a little confused with the documentation.

**The [ReadME.md states](https://github.com/chef-cookbooks/chef-server#addons) that:**
```
addons

Chef addons are premium features that can be installed on the Chef Server with the appropriate license. If there are < 25 nodes managed, or a paid subscription license, addons can be installed.

This recipe iterates through the node['chef-server']['addons'] attribute and installs and reconfigures all the packages listed.
```
Great!  "Where can I find a list of the addons supported in this cookbook?"  Where is it appropriate to use something else?

**Re: configurations, the ReadME.md states:**
```
Previous versions of this cookbook used configuration as a Hash. This is now deprecated and the configuration should be specified as a String. This must include newlines for each of the configuration items.
```
Great!  "Where can I find an example of configurations used this way?  Something a little more involved than setting up the notification email?"

If someone wants to drop some knowledge on me in-ticket, I'm happy to write up a PR for the ReadME.md.

Regards,
Joe Reid

**Comment by PierreRambaud** [comment]
Hi,

At least for chef server configuration you can have a look here: https://github.com/chef-cookbooks/chef-server/blob/master/attributes/default.rb#L30

Regards

**Comment by mistroh** [comment]
Hello,
I'm a little confused on the documentation as well.  What is the format that the addon attribute should be listed in in the cookbook?

For example, I'm trying to add the 'manage' addon to my Chef Server.  I see that the recipe is supposed to iterate through the node.default['chef-server']['addons'] attribute, but what format (how should I have) the addons listed in the array?

For example, the documentation shows how to configure the Chef Server configuration attributes (shown below), but I don't know how to configure the Addon attributes.  

```
node.default['chef-server']['configuration'] = <<-EOS
  notification_email '##########'
  api_fqdn '#{node["fqdn"]}'
EOS
```

Thanks.
