### ISSUE TITLE
Remove Gemfile, update TESTING.md

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/chef-server#97]
It is now considered best practice for cookbook developers to have ChefDK installed at the latest version. It contains the required gems to run test kitchen with vagrant and chefspec for testing this cookbook.

**Comment by PierreRambaud** [comment]
We already have this discussion on https://github.com/openstack/openstack-chef-repo, and even if it's a good practice to use ChefDk, not everybody use it nor wanna use it. 
Personally, I like to use Bundler, Rbenv, and manage multiple chef version easily with this tools.
It's also easier to use travis with Gemfile, force contributions on some cookbook to use rubocop, etc..
Developers must have the choice of their weapons!

**Comment by jtimberman** [comment]
Ah, I forgot about Travis.
