### ISSUE TITLE
Reconfigure is not working properly for opscode-manage config

### ISSUE THREAD

**Issue by Roviluca** [chef-cookbooks/chef-server#98]
Good evening,

i figured out that when i change the configuration of  attribute ['chef-server']['configuration'] the reconfigure is notified only to chef-server and not to the addons that use it. 
As a test I have tried to change ldap['system_adjective'] and opscode-manage wasn't reconfigured automatically. (Maybe also the fist opscode-manage-ctl reconfigure is missing)

Since  ['chef-server']['configuration']  turns out to be a very long sting '\n' separated maybe it could be splitted in single elements with specified the service they must notify or in chunks.

thanks in advance
Luca

**Comment by sersut** [comment]
Thanks for filing this @Roviluca. Looks like `ldap['system_adjective']` is a special option which exists in chef-server config but used by manage ([ref](https://docs.chef.io/server_ldap.html)). 

There are a couple of options. You can go towards using `chef_ingredient` resource directly (more info here: https://github.com/chef-cookbooks/chef-ingredient) by adding this line:

```Ruby
  notifies "chef_ingredient[manage]", :reconfigure
```

or you can use this resource to reconfigure manage:

```Ruby
chef_ingredient 'manage' do 
  action :reconfigure
end 
```
